### ISSUE TITLE
reimagine main nav menu

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/usf-imars.github.io#2]
We need a tree of what we want on the "new" main navigation menu. 

Here's the "old" one:
![image](https://user-images.githubusercontent.com/1051390/39487301-3e23f620-4d6e-11e8-89ce-5a2a927ba9ed.png)

Here is what I remember from our discussion:

* products
    * data
        * sat images
    * tools
        * mbon explorer
        * infographiq / infographics
* publications (external link to google scholar, research gate, or other)
* team
    * staff
    * students
    * alumni
* International Ocean Institute
* projects
    * ...
* contact
* outreach

**Comment by cjrmbon** [comment]
Yes, this is what we discussed. 

Just need to add the International Ocean Institute

**Comment by cjrmbon** [comment]
Need to add one more category to the menu -- Outreach.
