### ISSUE TITLE
identify jekyll template we want to start from

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/usf-imars.github.io#3]
from looking over jekyllthemes.org ...

from @cjrmbon :
> Instead of writing a report, I looked at all 17 pages of Jekyll themes. Found 4 templates that fit my design notion of a science-oriented landing page. I most liked the design support for number 1. Let me know if you have other options too. 
    https://phlow.github.io/feeling-responsive/
    https://janczizikow.github.io/sleek/
    http://webjeda.com/karna/
    http://jekyllthemes.org/themes/jekyll-mdl/

**Comment by 7yl4r** [comment]
Of those 4 I would prefer one of the first two.

**Comment by cjrmbon** [comment]
Cool. They are in rank order of my preferences. Feel free to search for more. Once you evaluate the "mechanics" we can decide.
