### ISSUE TITLE
identify publication list service we want to use

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/usf-imars.github.io#5]
eg google scholar, researchgate

We want to:
1. link to user page w/ publication list
2. list all publications within a group or with certain label (eg "imars", "mbon")

**Comment by 7yl4r** [comment]
Can google groups do (2)? [maybe, sort of](https://www2.le.ac.uk/library/downloads/research-services/UoL_Google_Scholar_Group_Profiles.pdf)

**Comment by 7yl4r** [comment]
[jekyll-scholar](https://github.com/inukshuk/jekyll-scholar) is an interesting extension which uses bibtex input. Although our users probably don't want to edit bibtex directly, you can export all of your publications from your google scholar profile easily:

![Uploading image.png…]()

**Comment by 7yl4r** [comment]
[jekyll-orcid](https://github.com/mfenner/jekyll-orcid) scrapes bibtex from OCRID.org - a service I have not heard of before, but looks good enough. The bibtex from there could also feed through `jekyll-scholar`.

**Comment by 7yl4r** [comment]
Zotero does user/group profiles too: [example group](https://www.zotero.org/groups/7666/forest_rights_act)

**Comment by 7yl4r** [comment]
After all this I am honestly leaning towards just leaving things as raw text.
These tools are great but the added value doesn't seem worth the trouble.
Please reopen and comment if you disagree.

**Comment by sebastiandig** [comment]
Yes, I find that is much better than Mendeley. It can also extract from Mendeley so you don't lose highlights or notes.
