### ISSUE TITLE
list of pages we want to port, link, or recreate from old site

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/usf-imars.github.io#6]
This is just for the first pass over the website

legend:
:link: = linked (old page is linked to from new website)
:new: = new page 
:recycle: = rework (new content)
:arrow_right: = port (mostly copy & paste)
:x: = broken link
:no_entry_sign: = empty page

-----------------------------

* :arrow_right: publications ported to external (see #5)
* :arrow_right: home page
* :link: satellite images/*
* projects
    * :link: cariaco
          * :x: cariaco en Espanol
          * :x: ocean time series data > HPLC data > Seabass
    * :arrow_right: CRW-DSS
       * :link: HotSpots
       * :link: Degree Heating Weeks
    * :arrow_right: Preventing Marine Debris
          * 🚫 Clean Community 2
    *  :arrow_right: coastal cities summit
    *  :arrow_right: millennium corals
        * :x: http://data.unep-wcmc.org/datasets/13
        *  :arrow_right: Mapping Philosophy
        * :arrow_right: Scientific Goals
        * :arrow_right: Methods
        * :arrow_right: Seascape
        * :arrow_right: Geomorphology/*
        * :x: Results
        * :arrow_right: Output Products
        * :arrow_right: Collaborations
        * :link: Legacy Millenium Corals Section
    * :arrow_right: oceanic atlas/*
    * :arrow_right: UAS
          * :x: contact us
    * :arrow_right: education  
          *  :x: Remote Sensing Tour > all in text links; + `what is remote sensing` adobe flash
     * :arrow_right: MBON Marine Biodiversity Observation Network 
* :arrow_right: international ocean institute - USA
* :arrow_right: IMaRS Team
* :arrow_right: contact
* :new: Outreach

---------------------------

:link: imars/MC/*
:x: imars/OA/*

---------------------------

Is that it? I feel like I must be missing a lot here.

**Comment by cjrmbon** [comment]
I added outreach.

**Comment by 7yl4r** [comment]
It is also worth noting what links are broken on the old website here.

**Comment by 7yl4r** [comment]
I think the list is pretty much complete
