### ISSUE TITLE
Publications Options

### ISSUE THREAD

**Issue by cjrmbon** [USF-IMARS/usf-imars.github.io#7]
IMARS website should have a comprehensive and easy to update list of publications. Right now, people cannot see the publications that are linked to projects or grants. Individual team members have some publications.   

Change for refreshed IMARS-- 

1. Tyler recommends using existing research publication services such as Research Gate or Google Scholar profiles to create group and links to show students, partners and alumni.  
2. Tyler to evaluate the different functions and choose a service, set up group (see #5). Then we can get IMARS team and students to update their profiles with tag etc  
3. Short-term -- collect publications from Frank's CV to circulate to IMARS team to develop a current list and post on the IMARS website as text on a page. This would be similar to the Optical Oceanography Lab which has a complete list of publications on their website.

http://optics.marine.usf.edu/references/publications_refereed.html

**Comment by 7yl4r** [comment]
Fairly good list over on #5 

Ultimately I lean towards plain text. 
Automating is nice, but if everyone isn't already using a system the added value might not be worth the trouble.
